# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Detailed configuration is in pyproject.toml:
# - [tool.ruff] for linting/formatting rules
# - [tool.mypy] for type checking configuration
# - [tool.pytest.ini_options] for test configuration
#
repos:
  # Ruff - Python linter and formatter (configuration in pyproject.toml)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      # Run the linter (uses pyproject.toml config)
      - id: ruff-check
        args: [--fix]
      # Run the formatter (uses pyproject.toml config)
      - id: ruff-format

  # Mypy - Static type checker (strict mode, config in pyproject.toml)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [
          mypy,
          types-requests,
          types-PyYAML,
        ]
        # Uses pyproject.toml [tool.mypy] configuration

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
      # Check TOML syntax
      - id: check-toml
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with newline
      - id: end-of-file-fixer
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=1000']
      # Check for debugger imports
      - id: debug-statements
      # Check for private key files
      - id: detect-private-key
